
performance:
  # upload-rate: 5000


jobs:
  - name: archive_job
    directories:
    - source: 'y:\' 
      destination: 'pictures'
      exclude-regex:
      - '.*\\thumbs.db'
      attr-exclude: S
    priority: 1
    # type: archive
    storage-account: jaysbackup
    # auth-key: 
    auth-key-file: "..\\..\\authkey.yml"
    metadata-cache-file: metadata.cache.bin
    archive:
      container: data-archive
    delta:
      container: data-delta
    history:
      container: data-history
      

    