
performance:
  # upload-rate: 5000
  schedule:
  - days:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    start: 0
    duration: 60

jobs:
  - name: archive_job
    directories:
    - source: 'y:\' 
      destination: 'pictures'
      include-regex:
      - 'C:\\Users\\.*\\Documents'
      exclude-regex:
      - '.*\\thumbs.db'
      attr-exclude:
      - System
    priority: 2
    # type: archive
    storage-account: jaysbackup
    # auth-key: 
    auth-key-file: "..\\..\\authkey.yml"
    metadata-cache-file: metadata.cache.bin
    archive:
      container: data-archive
    delta:
      container: data-delta
    history:
      container: data-history
  - name: test_job
    directories:
    - source: 'c:\Users\' 
      destination: 'docs'
      include-regex:
      - 'C:\\Users\\.*\\Documents'
      - 'C:\\Users\\.*\\Pictures'
      - 'C:\\Users\\.*\\Music'
      #exclude-regex:
      #- '.*\\thumbs.db'
      attr-exclude:
      - System
    priority: 1
    # type: archive
    storage-account: jaysbackup
    # auth-key: 
    auth-key-file: "..\\..\\authkey.yml"
    metadata-cache-file: metadata.cache.bin
    archive:
      container: test-archive
    delta:
      container: test-delta
    history:
      container: test-history
      

    